Adds no-notices flag
staabm/annotate-pull-request-from-checkstyle pull request #69
Opened 2021-05-07 18:09 UTC by donatj

GitHub Actions don't actually have a notice level, so they just get added to the log but not the file tab

![image](https://user-images.githubusercontent.com/133747/117490674-b8e35b00-af34-11eb-97aa-cbef4ff6aff5.png)

This PR just adds a `--no-notices` flag that lets you have them as GitHub warnings.

2021-05-07 20:45 UTC, staabm commented
Hmm.. per docs `notice` is a valid annotation level, see https://docs.github.com/en/rest/reference/checks#check-runs

<img width="1024" alt="PNG-Bild" src="https://user-images.githubusercontent.com/120441/117506429-de4c8500-af85-11eb-9c60-5e9d3ee10130.png">

2021-05-07 22:03 UTC, donatj commented
@staabm  The checks API supports creating notices, but not action commands

https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message

2021-05-07 22:06 UTC, donatj commented
There's also debug, but it behaves differently and doesn't have filename/line support.

![image](https://user-images.githubusercontent.com/133747/117513061-83e80000-af56-11eb-8de8-92e614c945a3.png)

2021-05-18 23:40 UTC, donatj commented
Looks like #61 backs me up too.

2021-05-19 05:44 UTC, staabm commented
I will have a look later today. Thx for the PR

2021-05-25 20:10 UTC, staabm commented on cs2pr
> +        case 'no-notices':
Thx for the PR. I like the change in general.

I feel this option should be named `notices-as-warnings` or similar.
Additionally the new option should be added to the help output.

lastly this PR changes the mode-bits of this file - did this change intentionally?

2021-05-25 20:47 UTC, donatj commented
> I feel this option should be named notices-as-warnings or similar.

`notices-as-warnings` sounds good me - naming things is one of the hardest parts of programming 😉 

> a unit test is also mandatory.

Got that added for you.

> lastly this PR changes the mode-bits of this file - did this change intentionally?

I did `chmod +x cs2pr`  so I could run `./cs2pr` while testing my changes. I can revert that if you'd like. However, I think it makes sense for it to be executable given the shebang on line 1

https://github.com/staabm/annotate-pull-request-from-checkstyle/blob/8bc869542d45abb2f0e6f3496ad67dbf9369f9a5/cs2pr#L1-L2

2021-05-25 20:51 UTC, donatj commented
Pushed a fix to try to match the coding standard.

2021-05-25 20:55 UTC, staabm requested changes
Thanks!

The new option should be added to the help output. 
Otherwise lgtm

2021-05-25 21:04 UTC, donatj commented
Fixed the remaining code style error, added help output

2021-05-25 21:06 UTC, staabm commented on cs2pr
> +    echo "  --notices-as-warnings Convert notices to warnings.\n";
```suggestion
    echo "  --notices-as-warnings Convert notices to warnings (Github does not annotate notices otherwise).\n";
```

2021-05-25 21:07 UTC, staabm approved these changes
Love it, thanks

2021-05-25 21:09 UTC, merged